# Generated by Django 4.1.2 on 2022-10-29 10:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0002_delete_tablets_phones_p_image'),
    ]

    operations = [
        migrations.CreateModel(
            name='Tablets',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('p_image', models.ImageField(upload_to='phoneimages')),
                ('t_name', models.CharField(max_length=100)),
                ('t_description', models.TextField()),
            ],
        ),
    ]
