# Generated by Django 4.1.2 on 2022-10-29 10:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0003_tablets'),
    ]

    operations = [
        migrations.CreateModel(
            name='Watches',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('w_image', models.ImageField(upload_to='phoneimages')),
                ('w_name', models.CharField(max_length=100)),
                ('w_description', models.TextField()),
            ],
        ),
        migrations.RenameField(
            model_name='tablets',
            old_name='p_image',
            new_name='t_image',
        ),
    ]
